### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by k0st1x** [kodi-game/game.libretro.mupen64plus-nx#10]
how to install n64 emulator to kodi on libreelec (rpi3)?
i cant find it in libreelec addons? should i install some repository?

**Comment by cnicodeme** [comment]
I agree here, could you provide any explanation how to do this? there is no explanations on the web to do so.

Thanks.

**Comment by k0st1x** [comment]
@garbear

**Comment by garbear** [comment]
N64 support requires OpenGL, and that is currently in the works. You can ask about further progress here: https://forum.kodi.tv/showthread.php?tid=351592
