### ISSUE TITLE
Kodi 20.1.0 Fail to install from zip 

### ISSUE THREAD

**Issue by gabrielecalvo** [kodi-game/game.libretro.mupen64plus-nx#16]
### Describe the bug

I couldn't find the add-on (or any other N64 add-ons) from the default repository so I came to this repo to download the latest release zip.
Unfortunately it fails to install with the following log message (degub log active already) below.

This issue is possibly related to https://github.com/kodi-game/game.libretro.mupen64plus-nx/issues/15

### To Reproduce

1. Download the [latest relase zip file](https://github.com/kodi-game/game.libretro.mupen64plus-nx/archive/refs/tags/2.5.0.37-Nexus.zip) to a directory kodi has access to
2. Go to "add-ons" > "Install from zip file" > select the downloaded file (game.libretro.mupen64plus-nx-2.5.0.37-Nexus.zip)
3. See the error message "Failed to install add-on from zip file"

### Debuglog

The debuglog can be found here:

> ...
> 2023-05-21 09:58:24.051 T:953     debug <general>: HandleKey: return (0xf00d) pressed, window 10126, action is Select
> 2023-05-21 09:58:24.310 T:953     debug <general>: ------ Window Deinit (FileBrowser.xml) ------
> 2023-05-21 09:58:24.335 T:953     debug <general>: CAddonInstaller: installing from zip '/storage/download/game.libretro.mupen64plus-nx-2.5.0.37-Nexus.zip'
> 2023-05-21 09:58:24.337 T:953     error <general>: CAddonInfoBuilder::Generate: Unable to load 'zip://%2fstorage%2fdownload%2fgame.libretro.mupen64plus-nx-2.5.0.37-Nexus.zip/game.libretro.mupen64plus-nx-2.5.0.37-Nexus/addon.xml', Line 0
>                                                    Failed to open file
> 2023-05-21 09:58:24.385 T:953     debug <general>: ------ Window Init (DialogNotification.xml) ------
> 2023-05-21 09:58:45.327 T:1351    debug <general>: Thread JobWorker 1400771200 terminating (autodelete)
> 2023-05-21 09:58:50.459 T:953     debug <general>: ------ Window Deinit (DialogNotification.xml) ------

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name:
LibreELEC 11.0.1, RPi2.arm

**Comment by lrusak** [comment]
On Linux binary add-ons are installed from your package manager.

Also, N64 (and other emulators that require OpenGL) aren't currently supported.
