### ISSUE TITLE
Unavailable under LibreELEC on RPi4 aarch64

### ISSUE THREAD

**Issue by physkets** [kodi-game/game.libretro.mupen64plus-nx#18]
### Describe the bug
Here is a clear and concise description of what the problem is:

I do not see this emulator along with a couple others like DeSmuME and Dolphin listed in the add-ons menus.

The list of supported platforms seem to be similar to a lot of the other add-ons that are available.

Why is that so?

## RetroArch Behavior
Here is a clear and concise description of what happens in RetroArch with the same core/game:

Have not tested.

### To Reproduce

Look for the emulator under: `Settings > Add-Ons > Install from repository > All repositories > Game add-ons > Emulators`

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name:

Kodi version: 21.1 (Omega)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
Kodi doesn't have OpenGL support, which is why this and other 3D add-ons aren't available. I think in Kodi they just crash. I created them so that our devs could have something to test while they work on OpenGL support, but development on that has been on-going for about 7 years now, so GL support probably won't arrive anytime soon.

**Comment by physkets** [comment]
I see.. is there an issue or PR in the Kodi repo that's tracking the work on OpenGL?

**Comment by physkets** [comment]
I think I found them:

https://github.com/xbmc/xbmc/issues/17743

https://github.com/xbmc/xbmc/issues/15874
